export { DonationComponent } from "./donation/donation.component";
export { HomeComponent } from "./home/home.component";
export { ExampleComponent } from "./example/example.component";
export { EditionComponent } from "./edition/edition.component";
export { ArtistsComponent } from "./artists/artists.component";
export { ArtistProfileComponent } from "./artistprofile/artistprofile.component";
export { ProfileComponent } from "./profile/profile.component";
export { GalleryComponent } from "./gallery/gallery.component";
export { TokenComponent } from "./token/token.component";
export { ActivityComponent } from "./activity/activity.component";
export { NewArtistComponent } from "./newArtist/newArtist.component";
export { RegisterArtistComponent } from "./register/register-artist/register-artist.component";
//export {InsertEditionComponent } from './artists/insertEdition/insertEdition.component';
export { PageNotFoundComponent } from "./page-not-found/page-not-found.component";
export { RegisterBuyerComponent } from "./register/register-buyer/register-buyer.component";
